id: P000090
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །སྤྱོད་འཇུག་གི་འབྲུ་འགྲེལ་དབུ་མའི་ལམ་གྱི་སྒྲོན་མ་ཞེས་བྱ་བ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  layers:
  - book_title
  - author
  - quotation
  - sabche
  id: KS-PK-05
web_metadata:
  title:
    en: A Lamp for the Middle Way:A Commentary on the Bodhicharyavatara
    bo: སྤྱོད་འཇུག་གི་འབྲུ་འགྲེལ་དབུ་མའི་ལམ་གྱི་སྒྲོན་མ་ཞེས་བྱ་བ་བཞུགས་སོ། །
  collection:
    en: Pema Karpo Series–  Book 5
    bo: ཀུན་མཁྱེན་གཞུང་འགྲེལ།–  དེབ། ༥
  author:
    en: Kunkhyen Pema Karpo
    bo: ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  pusblisher:
    en: Gautam Buddha Vihara
    bo: དོན་བརྒྱུད་དཔལ་ལྡན་འབྲུག་པ།
  sku: KS-PK-05
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: KS-PK-05.epub
  description:
    en: ''
    bo: ''
